#!/usr/bin/env sh

# Get the path to pvim
export PVIM="$(dirname "$(readlink -e -- "$0")")"

downloadAppimage() {
  if $appimageNeeded && [ "$imageLocation" = "$PVIM/nvim.appimage" ]; then
    appimageNeeded=false
    echo "Downloading latest Neovim"
    [ -f "$imageLocation" ] && rm "$imageLocation"
    curl -Lo "$imageLocation" https://github.com/neovim/neovim/releases/download/nightly/nvim-linux-x86_64.appimage && chmod u+x "$imageLocation"
  fi
}

updatepvim() {
  echo "Updating pvim"
  git --git-dir="$PVIM/.git" --work-tree="$PVIM" pull

  echo "Updating the config"
  git --git-dir="$PVIM/config/.git" --work-tree="$PVIM/config" pull

  if [ "$nvim" != "nvim" ]; then
    downloadAppimage
  fi
}

dashU=false
dashF=false
imageLocation="$PVIM/nvim.appimage"
dashH=false
optrem=1
while getopts ':ui:fh' opts; do
  case $opts in
    u)
      dashU=true
      ;;
    f)
      dashF=true
      ;;
    i)
      imageLocation="$OPTARG"
      ;;
    h)
      dashH=true
      ;;
    --)
      break
      ;;
    *)
      #Don't shift options that are meant for nvim
      optrem=$((optrem+1))
      ;;
  esac
done
shift $((OPTIND-optrem))

# Determine what Neovim to use
if [ -f "$imageLocation" ]; then
  nvim="$imageLocation"
elif command -v nvim > /dev/null && ! $dashF; then
  nvim="nvim"
else
  downloadAppimage
  nvim="$imageLocation"
fi

if $dashH; then
  echo "Usage:
  pvim [options] [neovimOptions]  Edit a file as your would with Neovim

Options:
  --                    Pass all following arguments to Neovim

  -u                    Update pvim, config(if git), and the appimage(if in use)
  -f                    Force the use of appimage over installed nvim
  -i <appimage>         specify the image path

Use \"pvim -- -h\" to see neovim help"
  exit
fi


if $dashU; then
  updatepvim
fi

export XDG_CONFIG_HOME="$PVIM/config"
export XDG_DATA_HOME="$PVIM/clutter/data"
export XDG_STATE_HOME="$PVIM/clutter/state"
export XDG_CACHE_HOME="$PVIM/clutter/cache"

#run Neovim with the local files
exec "$nvim" -i "$PVIM/clutter/shada/state" "$@"
